import { PropsWithChildren } from "react";

import Head from 'next/head'
import Navigation from "~/components/navbar/navigation";

interface LayoutProps extends PropsWithChildren {

}

const DefaultLayout = ({ children}: PropsWithChildren) => {

    return (
        <>
            <Head>
                <title>CV.AI</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='max-w-6xl mx-auto'>
                <Navigation />
                { children }
            </main>
        </>
        
    )

}

export default DefaultLayout