import { PropsWithChildren } from "react";

import Head from 'next/head'
import Navigation from "~/components/navbar/navigation";

interface LayoutProps extends PropsWithChildren {
    includeNav?: boolean
}

const DefaultLayout = ({ children, includeNav=true }: LayoutProps) => {

    return (
        <>
            <Head>
                <title>CV.AI</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {
                    includeNav && (
                        <div className="mx-w-6xl mx-auto">
                            <Navigation />
                        </div>
                    )
                }
                { children }
            </main>
        </>
        
    )

}

export default DefaultLayout